# Google Cloud Platform Configuration for SummerAI
# Email Alert Dashboard Project Configuration

# Project Details
project_id: famous-rhythm-465100-p6
project_name: "SummerAI Email Alert Dashboard"
organization_domain: summerai.biz
primary_admin: shuping@summerai.biz

# Regional Configuration
primary_region: us-east1
primary_zone: us-east1-b
backup_region: us-east4
backup_zone: us-east4-a

# Service Configuration
services:
  main_app:
    name: email-alert-dashboard
    type: cloud-run
    region: us-east1
    port: 8080
    
  database:
    type: cloud-sql
    instance_type: db-f1-micro
    region: us-east1
    
  storage:
    bucket_name: summerai-email-alerts-storage
    region: us-east1
    storage_class: STANDARD

# Network Configuration
network:
  vpc_name: summerai-vpc
  subnet_name: summerai-subnet
  firewall_rules:
    - name: allow-https
      direction: INGRESS
      ports: [443, 80]
    - name: allow-streamlit
      direction: INGRESS
      ports: [8080]

# IAM Configuration
iam:
  admin_users:
    - shuping@summerai.biz
  
  service_accounts:
    - name: email-alert-service
      description: "Service account for email alert dashboard"
      roles:
        - roles/cloudsql.client
        - roles/storage.objectAdmin
        - roles/secretmanager.secretAccessor
        
    - name: deployment-service
      description: "Service account for CI/CD deployments"
      roles:
        - roles/run.admin
        - roles/iam.serviceAccountUser

# Security Configuration
security:
  enable_audit_logs: true
  enable_vpc_flow_logs: true
  require_ssl: true
  
# Monitoring & Logging
monitoring:
  enable_cloud_monitoring: true
  enable_cloud_logging: true
  alert_policies:
    - name: high-cpu-usage
      threshold: 80
    - name: high-memory-usage
      threshold: 85
    - name: error-rate
      threshold: 5

# Backup Configuration
backup:
  database_backup_schedule: "0 2 * * *"  # Daily at 2 AM
  retention_days: 30
  
# Cost Management
cost_management:
  budget_amount: 100  # USD per month
  budget_alerts:
    - threshold: 50
      emails: [shuping@summerai.biz]
    - threshold: 80
      emails: [shuping@summerai.biz]
    - threshold: 100
      emails: [shuping@summerai.biz]

# Environment Variables (to be set in Secret Manager)
secrets:
  - name: GMAIL_USERNAME
    description: "Gmail username for email alerts"
  - name: GMAIL_PASSWORD
    description: "Gmail app password"
  - name: ANTHROPIC_API_KEY
    description: "Anthropic Claude API key"
  - name: ADMIN_PASSWORD
    description: "Admin dashboard password"
  - name: SESSION_SECRET
    description: "Session encryption secret"
