name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - feature/financial-metrics-extraction
  workflow_dispatch:

env:
  PROJECT_ID: portcoupdate2025
  SERVICE: tweener-insights
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/443349491696/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-actions@portcoupdate2025.iam.gserviceaccount.com'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE }} \
          --source . \
          --region ${{ env.REGION }} \
          --port 8501 \
          --memory 1Gi \
          --allow-unauthenticated \
          --quiet