name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - feature/financial-metrics-extraction
  workflow_dispatch:

env:
  PROJECT_ID: portcoupdate2025
  SERVICE: tweener-insights
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Google Auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE }} \
          --source . \
          --region ${{ env.REGION }} \
          --port 8501 \
          --memory 1Gi \
          --allow-unauthenticated \
          --quiet