[theme]
# Primary accent color for interactive elements
primaryColor = "#4fd1c7"  # Tweener Fund teal

# Background color for the main content area
backgroundColor = "#0E1117"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#262730"

# Color used for almost all text
textColor = "#FAFAFA"

# Font family for all text in the app
font = "sans serif"

[server]
# Port to use for the app
port = 8501

# Enable CORS protection
enableCORS = true

# Enable hot reloading
runOnSave = true

# Headless mode for cloud deployment
headless = true

# Max upload size (100MB)
maxUploadSize = 100

[browser]
# Internet address where users should point their browsers to connect to the app
serverAddress = "0.0.0.0"

# Whether to send Streamlit usage stats
gatherUsageStats = false

[client]
# Show error details
showErrorDetails = false

# Toolbar mode
toolbarMode = "minimal"